// Doctor data from Excel - Dr Data tab
// Coordinates are approximate city center coordinates

import type { InsertDoctor } from "@shared/schema";

// City coordinates mapping
const CITY_COORDINATES: Record<string, { lat: string; lng: string }> = {
  "Sydney": { lat: "-33.8688", lng: "151.2093" },
  "Wollongong": { lat: "-34.4278", lng: "150.8931" },
  "Canberra": { lat: "-35.2809", lng: "149.1300" },
  "Melbourne": { lat: "-37.8136", lng: "144.9631" },
  "Greensborough": { lat: "-37.7000", lng: "145.1167" },
  "Brisbane": { lat: "-27.4698", lng: "153.0251" },
  "Craigie": { lat: "-31.7833", lng: "115.7667" },
};

// Helper function to get coordinates for a city
function getCoordinates(city: string): { lat: string; lng: string } | undefined {
  return CITY_COORDINATES[city];
}

// Helper function to create address with city, state, and location
function createAddress(city: string, state: string, clinicName: string): string {
  return `${clinicName}, ${city}, ${state}`;
}

export const DOCTOR_DATA_SEED: InsertDoctor[] = [
  {
    name: "Dr Frank Quinn",
    specialty: "IVF, leadership",
    clinic: "IVF Australia Miranda",
    location: "Sydney",
    address: createAddress("Sydney", "NSW", "IVF Australia Miranda"),
    latitude: getCoordinates("Sydney")?.lat,
    longitude: getCoordinates("Sydney")?.lng,
    phone: "0295161600",
    email: "info@ivf.com.au",
    bulkBilling: false,
  },
  {
    name: "Dr Andrew Hedges",
    specialty: "IVF",
    clinic: "IVF Australia Miranda",
    location: "Sydney",
    address: createAddress("Sydney", "NSW", "IVF Australia Miranda"),
    latitude: getCoordinates("Sydney")?.lat,
    longitude: getCoordinates("Sydney")?.lng,
    phone: "0295161600",
    email: "info@ivf.com.au",
    bulkBilling: false,
  },
  {
    name: "Dr Peter Leung",
    specialty: "IVF",
    clinic: "IVF Australia Wollongong",
    location: "Wollongong",
    address: createAddress("Wollongong", "NSW", "IVF Australia Wollongong"),
    latitude: getCoordinates("Wollongong")?.lat,
    longitude: getCoordinates("Wollongong")?.lng,
    phone: "0242259900",
    email: "info@ivf.com.au",
    bulkBilling: false,
  },
  {
    name: "Dr Steven Adair",
    specialty: "IVF",
    clinic: "IVF Australia Canberra",
    location: "Canberra",
    address: createAddress("Canberra", "ACT", "IVF Australia Canberra"),
    latitude: getCoordinates("Canberra")?.lat,
    longitude: getCoordinates("Canberra")?.lng,
    phone: "0262827381",
    email: "info@ivf.com.au",
    bulkBilling: false,
  },
  {
    name: "Dr Derek Lok",
    specialty: "IVF, recurrent loss",
    clinic: "Connect IVF Sydney",
    location: "Sydney",
    address: createAddress("Sydney", "NSW", "Connect IVF Sydney"),
    latitude: getCoordinates("Sydney")?.lat,
    longitude: getCoordinates("Sydney")?.lng,
    phone: "0292646200",
    email: "enquiries@connectivf.com.au",
    bulkBilling: false,
  },
  {
    name: "Dr Martin Healey",
    specialty: "IVF, endometriosis",
    clinic: "Melbourne IVF Collingwood",
    location: "Melbourne",
    address: createAddress("Melbourne", "VIC", "Melbourne IVF Collingwood"),
    latitude: getCoordinates("Melbourne")?.lat,
    longitude: getCoordinates("Melbourne")?.lng,
    phone: "0394260666",
    email: "info@melbourneivf.com.au",
    bulkBilling: false,
  },
  {
    name: "Dr Nicole Hope",
    specialty: "IVF",
    clinic: "Melbourne IVF Collingwood",
    location: "Melbourne",
    address: createAddress("Melbourne", "VIC", "Melbourne IVF Collingwood"),
    latitude: getCoordinates("Melbourne")?.lat,
    longitude: getCoordinates("Melbourne")?.lng,
    phone: "0394260666",
    email: "info@melbourneivf.com.au",
    bulkBilling: false,
  },
  {
    name: "Dr Sameer Jatkar",
    specialty: "IVF",
    clinic: "Melbourne IVF Collingwood",
    location: "Melbourne",
    address: createAddress("Melbourne", "VIC", "Melbourne IVF Collingwood"),
    latitude: getCoordinates("Melbourne")?.lat,
    longitude: getCoordinates("Melbourne")?.lng,
    phone: "0394260666",
    email: "info@melbourneivf.com.au",
    bulkBilling: false,
  },
  {
    name: "Dr Chris Russell",
    specialty: "IVF",
    clinic: "Melbourne IVF Collingwood",
    location: "Melbourne",
    address: createAddress("Melbourne", "VIC", "Melbourne IVF Collingwood"),
    latitude: getCoordinates("Melbourne")?.lat,
    longitude: getCoordinates("Melbourne")?.lng,
    phone: "0394260666",
    email: "info@melbourneivf.com.au",
    bulkBilling: false,
  },
  {
    name: "Dr Hugo Fernandes",
    specialty: "IVF",
    clinic: "Melbourne IVF Collingwood",
    location: "Melbourne",
    address: createAddress("Melbourne", "VIC", "Melbourne IVF Collingwood"),
    latitude: getCoordinates("Melbourne")?.lat,
    longitude: getCoordinates("Melbourne")?.lng,
    phone: "0394260666",
    email: "info@melbourneivf.com.au",
    bulkBilling: false,
  },
  {
    name: "Dr Amber Kennedy",
    specialty: "IVF",
    clinic: "Melbourne IVF Collingwood",
    location: "Melbourne",
    address: createAddress("Melbourne", "VIC", "Melbourne IVF Collingwood"),
    latitude: getCoordinates("Melbourne")?.lat,
    longitude: getCoordinates("Melbourne")?.lng,
    phone: "0394260666",
    email: "info@melbourneivf.com.au",
    bulkBilling: false,
  },
  {
    name: "Prof Peter Illingworth",
    specialty: "IVF, research",
    clinic: "Westmead Fertility Centre",
    location: "Sydney",
    address: createAddress("Sydney", "NSW", "Westmead Fertility Centre"),
    latitude: getCoordinates("Sydney")?.lat,
    longitude: getCoordinates("Sydney")?.lng,
    phone: "0288907484",
    email: "fertility@health.nsw.gov.au",
    bulkBilling: false,
  },
  {
    name: "Dr Martyn Stafford-Bell",
    specialty: "IVF",
    clinic: "IVF Australia Canberra",
    location: "Canberra",
    address: createAddress("Canberra", "ACT", "IVF Australia Canberra"),
    latitude: getCoordinates("Canberra")?.lat,
    longitude: getCoordinates("Canberra")?.lng,
    phone: "0262827381",
    email: "info@ivf.com.au",
    bulkBilling: false,
  },
  {
    name: "Dr Chandra Krishnan",
    specialty: "IVF",
    clinic: "IVF Australia Miranda",
    location: "Sydney",
    address: createAddress("Sydney", "NSW", "IVF Australia Miranda"),
    latitude: getCoordinates("Sydney")?.lat,
    longitude: getCoordinates("Sydney")?.lng,
    phone: "0295161600",
    email: "info@ivf.com.au",
    bulkBilling: false,
  },
  {
    name: "Dr Paul Atkinson",
    specialty: "National Medical Director & Fertility Specialist",
    clinic: "Adora Fertility",
    location: "Sydney",
    address: createAddress("Sydney", "NSW", "Adora Fertility"),
    latitude: getCoordinates("Sydney")?.lat,
    longitude: getCoordinates("Sydney")?.lng,
    phone: "0291389800",
    email: "info@adorafertility.com.au",
    bulkBilling: false,
  },
  {
    name: "Dr Nalini Gayer",
    specialty: "Fertility Specialist",
    clinic: "Adora Fertility",
    location: "Sydney",
    address: createAddress("Sydney", "NSW", "Adora Fertility"),
    latitude: getCoordinates("Sydney")?.lat,
    longitude: getCoordinates("Sydney")?.lng,
    phone: "0291389800",
    email: "info@adorafertility.com.au",
    bulkBilling: false,
  },
  {
    name: "Dr Janelle McDonald",
    specialty: "Fertility Specialist",
    clinic: "Adora Fertility",
    location: "Sydney",
    address: createAddress("Sydney", "NSW", "Adora Fertility"),
    latitude: getCoordinates("Sydney")?.lat,
    longitude: getCoordinates("Sydney")?.lng,
    phone: "0291389800",
    email: "info@adorafertility.com.au",
    bulkBilling: false,
  },
  {
    name: "Dr Charley Zheng",
    specialty: "Fertility Specialist",
    clinic: "Adora Fertility",
    location: "Sydney",
    address: createAddress("Sydney", "NSW", "Adora Fertility"),
    latitude: getCoordinates("Sydney")?.lat,
    longitude: getCoordinates("Sydney")?.lng,
    phone: "0291389800",
    email: "info@adorafertility.com.au",
    bulkBilling: false,
  },
  {
    name: "Dr Julie Whitehead",
    specialty: "Clinical Director & Fertility Specialist",
    clinic: "Adora Fertility",
    location: "Greensborough",
    address: createAddress("Greensborough", "VIC", "Adora Fertility"),
    latitude: getCoordinates("Greensborough")?.lat,
    longitude: getCoordinates("Greensborough")?.lng,
    phone: "0291389800",
    email: "info@adorafertility.com.au",
    bulkBilling: false,
  },
  {
    name: "Dr Stephanie Sii",
    specialty: "Fertility Specialist",
    clinic: "Adora Fertility",
    location: "Greensborough",
    address: createAddress("Greensborough", "VIC", "Adora Fertility"),
    latitude: getCoordinates("Greensborough")?.lat,
    longitude: getCoordinates("Greensborough")?.lng,
    phone: "0291389800",
    email: "info@adorafertility.com.au",
    bulkBilling: false,
  },
  {
    name: "Dr Oybek Rustamov",
    specialty: "Clinical Director & Fertility Specialist",
    clinic: "Adora Fertility",
    location: "Brisbane",
    address: createAddress("Brisbane", "QLD", "Adora Fertility"),
    latitude: getCoordinates("Brisbane")?.lat,
    longitude: getCoordinates("Brisbane")?.lng,
    phone: "0291389800",
    email: "info@adorafertility.com.au",
    bulkBilling: false,
  },
  {
    name: "Dr Susan George",
    specialty: "Fertility Specialist",
    clinic: "Adora Fertility",
    location: "Brisbane",
    address: createAddress("Brisbane", "QLD", "Adora Fertility"),
    latitude: getCoordinates("Brisbane")?.lat,
    longitude: getCoordinates("Brisbane")?.lng,
    phone: "0291389800",
    email: "info@adorafertility.com.au",
    bulkBilling: false,
  },
  {
    name: "Dr Gayatri Borude",
    specialty: "Clinical Director & Fertility Specialist",
    clinic: "Adora Fertility",
    location: "Craigie",
    address: createAddress("Craigie", "WA", "Adora Fertility"),
    latitude: getCoordinates("Craigie")?.lat,
    longitude: getCoordinates("Craigie")?.lng,
    phone: "0291389800",
    email: "info@adorafertility.com.au",
    bulkBilling: false,
  },
  {
    name: "Dr Mahalakshmi Ragunath",
    specialty: "Fertility Specialist",
    clinic: "Adora Fertility",
    location: "Craigie",
    address: createAddress("Craigie", "WA", "Adora Fertility"),
    latitude: getCoordinates("Craigie")?.lat,
    longitude: getCoordinates("Craigie")?.lng,
    phone: "0291389800",
    email: "info@adorafertility.com.au",
    bulkBilling: false,
  },
  {
    name: "Dr Shanthi Srinivasan",
    specialty: "Fertility Specialist",
    clinic: "Adora Fertility",
    location: "Craigie",
    address: createAddress("Craigie", "WA", "Adora Fertility"),
    latitude: getCoordinates("Craigie")?.lat,
    longitude: getCoordinates("Craigie")?.lng,
    phone: "0291389800",
    email: "info@adorafertility.com.au",
    bulkBilling: false,
  },
];
